@baseUrl = http://localhost:3000


### lista todos recados
GET {{baseUrl}}/recados

### pega um recado pelo id
GET {{baseUrl}}/recados/6a

### cria um recado
POST {{baseUrl}}/recados
Content-Type: application/json

{
  "texto": "Novo recado 17:30",
  "deId": 4,
  "paraId": 4
}

### atualiza um recado
PATCH {{baseUrl}}/recados/3
Content-Type: application/json

  {
    "texto": "Recado atualizado",
    "de": "Alice",
    "para": "Bob",
    "lido": false,
    "data": "2025-10-12T20:36:29.855Z"
  }



  // =-=-=-=-=-=-=-=-=-=-PESSOA
### cria uma pessoa
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Luan Vidal",
  "email": "luan.vidal@gmail.com",
  "password": "Abc123456!@#"
}

